data:
  # Directories
  input_path: "/home/hippo/Joan/stroke-func-test/"
  output_path: "/home/hippo/Joan/stroke-func-test/bids-func-test/"
  ## Others ##
  gzip: True
  log: True

# Subject to process
subjects: 
  # Folders to process
  folders: "fcs-57c2" #"fcs-57c2"
  # MRI images
  mris: ['anat','dwi','func']
