data:
  # Directories
  ## Cla ##
  input_path: "/home/bam/Joan/StrokeDatasetV2/"
  output_path: "/home/bam/Joan/Stroke_WUSM/"
  ## Thinkpad ##
  #input_path: "/home/joan/Desktop/StrokeDatasetV2/"
  #output_path: "/home/joan/Documents/Stroke_WUSM/"
  ## Others ##
  gzip: True

# Subject to process
subjects: 
  # Folders to process
  folders: "FCS87*" #"fcs-57c2"
  # MRI images
  mris: ['anat','dwi','fMRI']
