data:
  # Directories
  ## Cla ##
  input_path: "/home/bam/Joan/StrokeDatasetV2/"
  output_path: "/home/bam/Joan/Stroke_WUSM/"
  ## Thinkpad ##
  input_path: "/home/joan/Downloads/PR-43C2/"
  output_path: "/home/joan/Downloads/43/"
  ## Others ##
  gzip: True
  log: True

# Subject to process
subjects: 
  # Folders to process
  folders: "*" #"fcs-57c2"
  # MRI images
  mris: ['anat'] #,'dwi','fMRI']
