data:
  # Directories
  input_path: "/home/joan/Desktop/StrokeDatasetV2/"
  output_path: "/home/joan/Documents/Stroke_WUSM/"
  # Output characteristics
  gzip: True

# Subject to process
subjects: 
  # Folders to process
  folders: "*" #"fcs-57c2"
  # MRI images
  mris: ['anat','dwi','fMRI']
